-- Corrected teams data
INSERT INTO teams (team_id, tri_code, city, team_name, team_logo, class_name)
VALUES
  (1, 'ANA', 'Anaheim', 'Anaheim Ducks', 'https://assets.nhle.com/logos/nhl/svg/ANA_light.svg', 'Anaheim'),
  (2, 'BOS', 'Boston', 'Boston Bruins', 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg', 'Boston'),
  (3, 'BUF', 'Buffalo', 'Buffalo Sabres', 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg', 'Buffalo'),
  (4, 'CGY', 'Calgary', 'Calgary Flames', 'https://assets.nhle.com/logos/nhl/svg/CGY_light.svg', 'Calgary'),
  (5, 'CAR', 'Carolina', 'Carolina Hurricanes', 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg', 'Carolina'),
  (6, 'CHI', 'Chicago', 'Chicago Blackhawks', 'https://assets.nhle.com/logos/nhl/svg/CHI_light.svg', 'Chicago'),
  (7, 'COL', 'Colorado', 'Colorado Avalanche', 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg', 'Colorado'),
  (8, 'CBJ', 'Columbus', 'Columbus Blue Jackets', 'https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg', 'Columbus'),
  (9, 'DAL', 'Dallas', 'Dallas Stars', 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg', 'Dallas'),
  (10, 'DET', 'Detroit', 'Detroit Red Wings', 'https://assets.nhle.com/logos/nhl/svg/DET_light.svg', 'Detroit'),
  (11, 'EDM', 'Edmonton', 'Edmonton Oilers', 'https://assets.nhle.com/logos/nhl/svg/EDM_light.svg', 'Edmonton'),
  (12, 'FLA', 'Florida', 'Florida Panthers', 'https://assets.nhle.com/logos/nhl/svg/FLA_light.svg', 'Florida'),
  (13, 'LAK', 'Los Angeles', 'Los Angeles Kings', 'https://assets.nhle.com/logos/nhl/svg/LAK_light.svg', 'LosAngeles'),
  (14, 'MIN', 'Minnesota', 'Minnesota Wild', 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg', 'Minnesota'),
  (15, 'MTL', 'Montreal', 'Montreal Canadiens', 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg', 'Montreal'),
  (16, 'NSH', 'Nashville', 'Nashville Predators', 'https://assets.nhle.com/logos/nhl/svg/NSH_light.svg', 'Nashville'),
  (17, 'NJD', 'New Jersey', 'New Jersey Devils', 'https://assets.nhle.com/logos/nhl/svg/NJD_light.svg', 'NewJersey'),
  (18, 'NYI', 'NY Islanders', 'New York Islanders', 'https://assets.nhle.com/logos/nhl/svg/NYI_light.svg', 'NewYorkI'),
  (19, 'NYR', 'NY Rangers', 'New York Rangers', 'https://assets.nhle.com/logos/nhl/svg/NYR_light.svg', 'NewYorkR'),
  (20, 'OTT', 'Ottawa', 'Ottawa Senators', 'https://assets.nhle.com/logos/nhl/svg/OTT_light.svg', 'Ottawa'),
  (21, 'PHI', 'Philadelphia', 'Philadelphia Flyers', 'https://assets.nhle.com/logos/nhl/svg/PHI_light.svg', 'Philadelphia'),
  (22, 'PIT', 'Pittsburgh', 'Pittsburgh Penguins', 'https://assets.nhle.com/logos/nhl/svg/PIT_light.svg', 'Pittsburgh'),
  (23, 'SJS', 'San Jose', 'San Jose Sharks', 'https://assets.nhle.com/logos/nhl/svg/SJS_light.svg', 'SanJose'),
  (24, 'SEA', 'Seattle', 'Seattle Kraken', 'https://assets.nhle.com/logos/nhl/svg/SEA_light.svg', 'Seattle'),
  (25, 'STL', 'St. Louis', 'St. Louis Blues', 'https://assets.nhle.com/logos/nhl/svg/STL_light.svg', 'StLouis'),
  (26, 'TBL', 'Tampa Bay', 'Tampa Bay Lightning', 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg', 'TampaBay'),
  (27, 'TOR', 'Toronto', 'Toronto Maple Leafs', 'https://assets.nhle.com/logos/nhl/svg/TOR_light.svg', 'Toronto'),
  (28, 'UTA', 'Utah', 'Utah Hockey Club', 'https://assets.nhle.com/logos/nhl/svg/UTA_light.svg', 'Utah'),
  (29, 'VAN', 'Vancouver', 'Vancouver Canucks', 'https://assets.nhle.com/logos/nhl/svg/VAN_light.svg', 'Vancouver'),
  (30, 'VGK', 'Vegas', 'Vegas Golden Knights', 'https://assets.nhle.com/logos/nhl/svg/VGK_light.svg', 'Vegas'),
  (31, 'WSH', 'Washington', 'Washington Capitals', 'https://assets.nhle.com/logos/nhl/svg/WSH_secondary_light.svg', 'Washington'),
  (32, 'WPG', 'Winnipeg', 'Winnipeg Jets', 'https://assets.nhle.com/logos/nhl/svg/WPG_light.svg', 'Winnipeg');