INSERT INTO players (
    id, 
    firstName, 
    lastName, 
    teamAbbreviation, 
    positionCode, 
    headshot, 
    sweaterNumber, 
    points, 
    goals, 
    assists, 
    plusMinus, 
    saves, 
    goalsAllowed, 
    savePercentage, 
    goalsAgainstAverage, 
    createdAt, 
    updatedAt
) VALUES (
    8474567,
    'Zach',
    'Bogosian',
    'MIN',
    'D',
    'https://assets.nhle.com/mugs/nhl/20242025/MIN/8474567.png',
    24,
    0,
    4,
    8,
    12,
    NULL,
    NULL,
    NULL,
    NULL,
    '2021-10-01 00:00:00',
    '2021-10-01 00:00:00'
);